import Head from 'next/head';
import '../src/output.css'
import '../src/style.sass'
import Script from 'next/script';
import Footer from './parts/footer_actions'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir='rtl' className='dark'>
      <body>
        <div id='container'>
          {children}
          <Footer items={[
            { 'url': '/', 'name': 'home' },
            { 'url': '/search', 'name': 'search-alt' },
            { 'url': '/checkout', 'name': 'shopping-bag' },
            { 'url': '/my', 'name': 'user' },
          ]} />
        </div>
      </body>
    </html>
  );
}
